include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_function_literals_in_foreach_calls: true
    directives_ordering: true
    omit_local_variable_types: false
    prefer_expression_function_bodies: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_relative_imports: true
    prefer_typing_uninitialized_variables: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true