name: dart_console
description: A starting point for Dart libraries or applications.
version: 0.1.0
author: Tim Sneath <timsneath@google.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.5
