name: dart_console
description: 
  A helper library for command-line applications that need more control over input/output than the standard library provides.

version: 0.6.0
homepage: https://github.com/timsneath/dart_console

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  win32: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
