name: dart_console
description: 
  A helper library for command-line applications that need more control over input/output than the standard library provides.

version: 0.3.0
homepage: https://github.com/timsneath/dart_console
author: Tim Sneath <timsneath@google.com>

environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.10
