name: dart_console
description: A library for command-line applications.
version: 0.1.0+1
homepage: https://github.com/timsneath/dart_console
author: Tim Sneath <timsneath@google.com>

environment:
  sdk: '>=2.5.0-dev.1 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.5
